# This is config file for git pre commit hooks
# It requires the pre-commit package from https://pre-commit.com/
# pre-commit is used to run git pre-commit hooks with
# a lot of pre-built hooks available on the website
#
# Install the pre-commit package and run pre-commit install
# from the git repository

# The following hook would install clang-format hook and
# run it for every commit. It would apply clang-format fixes
# and leave them as unstaged.
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        types: [c, c++, cuda]
